name: expo_sensors
description: A Flutter plugin for the expo-sensors Universal Module.
version: 0.1.0
authors:
- Juwan Wheatley <juwan@expo.io>
homepage: https://github.com/expo/expo/tree/master/packages/expo-sensors-flutter-plugin

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  expo_flutter_adapter: ^0.1.0

flutter:
  plugin:
    androidPackage: io.expo.exposensors
    pluginClass: ExpoSensorsPlugin
