name: Native Component List app

on:
  workflow_dispatch: {}
  pull_request:
    branches: [master]
    paths:
      - .github/workflows/native-component-list.yml
      - apps/native-component-list/**
      - yarn.lock
  push:
    branches: [master]
    paths:
      - .github/workflows/native-component-list.yml
      - apps/native-component-list/**
      - yarn.lock

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --frozen-lockfile
      - run: yarn tsc
        working-directory: apps/native-component-list
      - run: yarn lint --max-warnings 0
        working-directory: apps/native-component-list
      - uses: 8398a7/action-slack@v3
        if: failure() && (github.event.ref == 'refs/heads/master')
        with:
          channel: '#api'
          status: ${{ job.status }}
          author_name: native-component-list/build
          fields: author,job,message,ref
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook_api }}
