name: SDK

on:
  push:
    branches: [master, 'sdk-*']
    paths:
      - .github/workflows/sdk.yml
      - tools/expotools/**
      - packages/**
      - yarn.lock
  pull_request:
    branches: [master]
    paths:
      - .github/workflows/sdk.yml
      - tools/expotools/**
      - packages/**
      - yarn.lock
  schedule:
    - cron: 0 14 * * *

jobs:
  check-packages:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout a ref for the event
        uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - name: Fetch commits from base branch
        run: git fetch origin ${{ github.base_ref }}:${{ github.base_ref }} --depth 100
        if: github.event_name == 'pull_request'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --frozen-lockfile
      - name: Check packages
        run: |
          echo "Checking packages according to the event name: ${{ github.event_name }}"
          if [[ ${{ github.event_name }} == "schedule" ]]; then
            # Check all packages on scheduled events
            bin/expotools check-packages --all
          elif [[ ${{ github.event_name }} == "push" ]]; then
            # On push event check packages changed since previous remote head
            bin/expotools check-packages --since ${{ github.event.before }}
          else
            # In pull requests check all packages changed in the entire PR
            bin/expotools check-packages --since ${{ github.base_ref }}
          fi
      - uses: 8398a7/action-slack@v3
        if: failure() && (github.event.ref == 'refs/heads/master' || startsWith(github.event.ref, 'refs/heads/sdk-'))
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook_api }}
        with:
          channel: '#api'
          status: ${{ job.status }}
          fields: author,job,message,ref
          author_name: sdk check-packages
