name: SDK

on:
  workflow_dispatch:
    inputs:
      checkAll:
        description: 'type "check-all" to force checking all packages'
        required: false
        default: ''
  push:
    branches: [master, 'sdk-*']
    paths:
      - .github/workflows/sdk.yml
      - tools/**
      - packages/**
      - yarn.lock
  pull_request:
    branches: [master]
    paths:
      - .github/workflows/sdk.yml
      - tools/**
      - packages/**
      - yarn.lock
  schedule:
    - cron: 0 14 * * *

jobs:
  check-packages:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout a ref for the event
        uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - name: Fetch commits from base branch
        run: git fetch origin ${{ github.event.before || github.base_ref || 'master' }}:${{ github.event.before || github.base_ref || 'master' }} --depth 100
        if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --frozen-lockfile
      - name: Check packages
        run: |
          echo "Checking packages according to the event name: ${{ github.event_name }}"
          if [[ "${{ github.event_name }}" == "schedule" || "${{ github.event.inputs.checkAll }}" == "check-all" ]]; then
            # Check all packages on scheduled events or if requested by workflow_dispatch event.
            bin/expotools check-packages --all
          else
            # On push event check packages changed since previous remote head.
            # In pull requests and workflow_dispatch events check all packages changed in the entire PR.
            bin/expotools check-packages --since ${{ github.event.before || github.base_ref || 'master' }}
          fi
      - uses: 8398a7/action-slack@v3
        if: failure() && (github.event.ref == 'refs/heads/master' || startsWith(github.event.ref, 'refs/heads/sdk-'))
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook_api }}
        with:
          channel: '#api'
          status: custom
          fields: author,commit,ref,workflow
          custom_payload: |
            {
              username: 'github-actions',
              icon_emoji: ':octocat:',
              attachments: [{
                color: 'danger',
                text: `${process.env.AS_WORKFLOW}@${process.env.AS_REF} failed: ${(process.env.AS_EVENT_NAME === 'schedule') ? 'scheduled build' : process.env.AS_COMMIT + ' by ' + process.env.AS_AUTHOR}`,
              }]
            }
